source 'https://rubygems.org'

gem 'rails', '7.1.0'

gem 'validatable', '>=1.6.0'

gem 'dynamic_form'

gem 'sprockets-rails', '>= 3.0.0'
gem 'sass-rails'
gem 'requirejs-rails', '>= 1.0.1'
gem 'mithril_rails'
gem 'uglifier'
gem 'foundation-rails'
gem 'bourbon'
gem 'font-awesome-sass'
gem 'js-routes', '>= 1.1.1'

gem 'oauth2_provider', '1.0.3', path: 'vendor/engines/oauth2_provider'
gem 'versionist', '>= 1.5.0'
gem 'roar', '>= 1.0.2'
gem 'rack-throttle', '~> 0.5.0'
gem 'webpack-rails', '>= 0.9.11'

group :development, :test do
  gem 'rails-dev-tweaks', '~> 1.1'
  gem 'minitest'
  gem "jasmine", ">= 2.3.1"
  gem "jasmine-rails", ">= 0.12.0"
  gem 'selenium-webdriver', '>= 2.53.1'
  gem 'jasmine-jquery-rails'
  gem 'jasmine-junitreporter'

  gem 'rspec-rails', '2.99.0'
  gem 'rspec-extra-formatters'

  gem 'capybara', '2.3.0'
  gem 'ruby-debug-base'
  gem 'ruby-debug-ide', '>= 0.6.1'
end
